//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAccountBalance", ReplyAction="http://tempuri.org/IService/GetAccountBalanceResponse")]
        string GetAccountBalance(int userId, string accountNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAccountBalance", ReplyAction="http://tempuri.org/IService/GetAccountBalanceResponse")]
        System.Threading.Tasks.Task<string> GetAccountBalanceAsync(int userId, string accountNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateBalance", ReplyAction="http://tempuri.org/IService/UpdateBalanceResponse")]
        string UpdateBalance(int userId, string accountNumber, string purchasedAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateBalance", ReplyAction="http://tempuri.org/IService/UpdateBalanceResponse")]
        System.Threading.Tasks.Task<string> UpdateBalanceAsync(int userId, string accountNumber, string purchasedAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : WebApplication2.ServiceReference2.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WebApplication2.ServiceReference2.IService>, WebApplication2.ServiceReference2.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetAccountBalance(int userId, string accountNumber) {
            return base.Channel.GetAccountBalance(userId, accountNumber);
        }
        
        public System.Threading.Tasks.Task<string> GetAccountBalanceAsync(int userId, string accountNumber) {
            return base.Channel.GetAccountBalanceAsync(userId, accountNumber);
        }
        
        public string UpdateBalance(int userId, string accountNumber, string purchasedAmount) {
            return base.Channel.UpdateBalance(userId, accountNumber, purchasedAmount);
        }
        
        public System.Threading.Tasks.Task<string> UpdateBalanceAsync(int userId, string accountNumber, string purchasedAmount) {
            return base.Channel.UpdateBalanceAsync(userId, accountNumber, purchasedAmount);
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
    }
}
